### ISSUE TITLE
ggplot coord_polar() issue with multiple classes: 'from' must be a finite number error

### ISSUE THREAD

**Issue by magnotairone** [AllanCameron/geomtextpath#104]
Hi all,

The code below works perfectly.
```
tibble(class = c("Class 1", "Class 2"),
       y = c(1:2),
       x1 = c(10,11),
       x2 = c(17,15)) %>% 
  ggplot(aes(x=x1, xend=x2, y=y, yend=y, label=class))+
  geom_textsegment()
```

However, when I add the `coord_polar()` layer, it gives me the following error 
```
tibble(class = c("Class 1", "Class 2"),
       y = c(1:2),
       x1 = c(10,11),
       x2 = c(17,15)) %>% 
  ggplot(aes(x=x1, xend=x2, y=y, yend=y, label=class))+
  geom_textsegment()+
  coord_polar()
```
Error:
``` 
Error in (function (from = 1, to = 1, by = ((to - from)/(length.out -  : 
  'from' must be a finite number
```
If my dataset contains only one row, say `Class 1`, then it works. The error arises in cases where I have more than one class. For example, the code below works
```
tibble(class = c("Class 1", "Class 2"),
       y = c(1:2),
       x1 = c(10,11),
       x2 = c(17,15)) %>% 
  filter(class=="Class 1") %>%
  ggplot(aes(x=x1, xend=x2, y=y, yend=y, label=class))+
  geom_textsegment()+
  coord_polar()
```

**Comment by teunbrand** [comment]
Because the scales in polar coordinates aren't expanded, the "Class 1" line is a line segment going from the center of the plot to the center of the plot and thus has 0 length. We can't really place text along a single point. In you plot, this can be fixed by expanding the y-axis with `scale_y_continuous(expand = expansion(add = 0.1))`. At best, we can try to intercept this and throw a better message, though I'm not sure this is a very common case.
