### ISSUE TITLE
Labeling simple features objects

### ISSUE THREAD

**Issue by samueldodson** [AllanCameron/geomtextpath#41]
Can this package label [simple features objects](https://ggplot2.tidyverse.org/reference/ggsf.html)? ggplot2 has the `geom_sf_label` and `geom_sf_text` functions for this; however, I would like to add labels along curvy lines / polylines (e.g., labeling a meandering river).

Here is an example of `geom_sf_text`: 

```{r}
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)

crop <- st_bbox(c(xmin = -84.74674,
                  xmax = -84.34674,
                  ymin = 42.5335,
                  ymax = 42.93353))

land <- ne_countries(scale = "medium",
                      returnclass = "sf") %>% st_crop(crop)

river <- ne_download(scale = 10,
                      type = "rivers_lake_centerlines",
                      category = "physical",
                      returnclass = "sf") %>% st_crop(crop)

ggplot() +
  geom_sf(data = land, fill = "cornsilk") +
  geom_sf(data = river, color = "blue") +
  geom_sf_text(data = river, aes(label = paste0(name, " River")), color = "blue")
```
...which outputs:

![Untitled1](https://user-images.githubusercontent.com/17250304/146619729-fa48eb83-19ae-49e5-a27d-ea9387f7d855.png)

Instead, I would like a curvy label:

![Untitled2](https://user-images.githubusercontent.com/17250304/146619746-7c238222-9cd9-4269-8e86-635e96e8d26e.png)

Can I do this with geomtextpath?

**Comment by teunbrand** [comment]
I'd say not *yet*, as the package is still young, but we've toyed with the idea and agreed that this would be a nice addition. Adjacent discussion happened [here](https://github.com/AllanCameron/geomtextpath/pull/38#issuecomment-995256698).

**Comment by AllanCameron** [comment]
Thanks for writing Samuel. Funnily enough, we have been discussing this recently and it's something we do have in the pipeline, hopefully in the next few days. I will keep this issue open as a feature request and keep you posted.

**Comment by AllanCameron** [comment]
@samueldodson  The latest commit brings rudimentary support for labels on rivers / linestring objects. When I attempted your example, I was unable to apply `st_crop` to the object `land` for some reason, so I have had to modify it to show what we have so far.
``` r
library(geomtextpath)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)

limits <- c(xmin = -84.74674,
            xmax = -84.34674,
            ymin = 42.5335,
            ymax = 42.93353)

crop <- st_bbox(limits)

land <- ne_countries(scale = "medium",
                      returnclass = "sf")

river <- ne_download(scale = 10,
                      type = "rivers_lake_centerlines",
                      category = "physical",
                      returnclass = "sf")

river <- st_crop(river, crop)

ggplot() + 
  geom_sf(data = land, fill = "cornsilk") +
  geom_textsf(data = river, label = "Grand River",
              color = "blue3", vjust = -0.4) +
  lims(x = limits[1:2], y = limits[3:4])
```
![image](https://user-images.githubusercontent.com/33987720/146844539-c09da340-453e-4466-9ec1-8e167c2d455f.png)

@teunbrand the main problem I'm having is the inability to smooth text at grob level. One cannot use `geom_smooth` in this context, so I may look at implementing this at some point. There are many problems to iron out, though by chance the example here works reasonably well.

**Comment by teunbrand** [comment]
> smooth text at grob level

Yes I was afraid we'd have to do this at the grob level at some point. Looking at [this blogpost](https://joeystanley.com/blog/geomtextpath), they also seem to indicate a preference to have the option to smooth text.

I've been giving this some thought and the problem with our current code is that we cannot, at the same time, do a path, draw that as-is and then also take the same path and smooth it and then draw the text over the smoothed path. 

However, what we might do in >R4.1 is to use a clipping mask as detailed in [Paul Murrell's report](https://developer.r-project.org/Blog/public/2020/07/15/new-features-in-the-r-graphics-engine/) from last year. We already have the code to draw a textbox along a curve, we can use that same code to generate a polygon that can act as a clipping mask for the path. I haven't experimented with this (yet), but we could use it to clip the original path while we place the text on a different path.

**Comment by AllanCameron** [comment]
I'm happy with the "suggests" rather than "imports".

I think we should be able to feed a smoothed version of the path to `get_path_points` (I forget it's new name already...) and keep the main path for the line.

The blog post shows some of the problems I was worried we might see in real - world examples, but at least the author isn't too critical.

**Comment by AllanCameron** [comment]
The latest commit adds the ability to remove text that is too long for its path. Along with the grob level text-smoothing, this was the main impediment to properly functioning labelled linestrings. The reason for this is that when zoomed out of a map, having every little river and road labelled causes massive overplotting. The new mechanism removes text from features that are too small to support them. Unfortunately, this also has to be done at grob level, but it is quite a cheap calculation, and is only done when specifically asked for (it's only turned on by default in `geom_textsf`), so it should not affect the performance of the rest of the package.

As shown in the updated readme, the resulting appearance of `geom_textsf` is now much more generally acceptable
``` r
crop_box <- sf::st_bbox(c(xmin = -4.8, xmax = -3.2, ymin = 55.5, ymax = 56.3))
df <- sf::st_crop(waterways, crop_box)
#> Warning: attribute variables are assumed to be spatially constant throughout all
#> geometries

ggplot(df) +
  geom_textsf(aes(label = name), text_smoothing = 99.5, linecolour = "#8888B3", 
              color = "gray30", hjust = 0.25, vjust = -0.5, fill = "#E6F0B3", 
              alpha = 0.8, fontface = 3, size = 3) + 
  theme(panel.grid = element_line()) + 
  lims(x = c(-4.7, -3.28), y = c(55.62, 56.25))
```

![image](https://github.com/AllanCameron/geomtextpath/raw/main/man/figures/README-geom_textsf-1.png)

While still not perfect, I think this could produce some very nice map-based plots that are not otherwise available at present in the ggplot ecosystem, and I am tempted to close this issue for now - unless there are any concerns @teunbrand ?
