### ISSUE TITLE
Preventing overplotting

### ISSUE THREAD

**Issue by AllanCameron** [AllanCameron/geomtextpath#49]
Text-based layers always run the risk of overplotting, and there are whole packages (like `ggrepel`) that aim to prevent it. Some plots will not work well with `geomtextpath` because of overplotting, and it would be useful to include some methods to prevent it.

Since we are largely using `vjust` and `hjust` to control text positioning, it seems sensible to me that we should allow these to be mapped to variables, so that mapping a discrete variable will by default allow wide separation of the labels. I have added a `scales.R` file that allows a full range of hjust and vjust scale functions.

Current behaviour is:
``` r
library(geomtextpath)
#> Loading required package: ggplot2

df <- data.frame(x = rep(0:1, each = 3), 
                 y = c(0, 2, 2.1), 
                 z = paste("Example", 1:3))

p <- ggplot(df, aes(x, y, label = z, group = z)) + ylim(c(0, 2.5))

p + geom_textline(size = 8) 
```

![](https://i.imgur.com/4iy06RE.png)

``` r
p + geom_textline(aes(vjust = z), size = 8) +
  scale_vjust_manual(values = c(-0.5, 1.5, -0.5))
```

![](https://i.imgur.com/YkVjMrm.png)

``` r
p + geom_textline(aes(vjust = z, hjust = z), size = 8) +
  scale_vjust_manual(values = c(-0.5, 1.5, -0.5))
```

![](https://i.imgur.com/3Kj56MC.png)

It might be a useful exercise to consider whether any other aesthetics could be usefully mapped to scales.

There are other options for preventing overplotting, such as collision detection etc, but this might be overkill? I would be interested to get your thoughts on this.

Another problem that crops up a lot on `geom_textsf` is that labels can sometimes be much longer than the linestrings. This produces long, straight, criss-crossing and ugly labels. It is quite easy to automatically remove such labels, but it needs to be done at `makeContent` level.

<sup>Created on 2022-01-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by teunbrand** [comment]
Yes overplotting is an issue with any geom you make and I don't think it is our power to counter every possible case of overlaps. Of course, the core business of {ggrepel} is to avoid overlapping text and while we might give some options to avoid it, the core of the package is to place text along paths.

There is an additional example I could think of that counters overplotting, and that is to use the labels to hide the overlapping bits.

``` r
library(geomtextpath)
#> Loading required package: ggplot2

df <- data.frame(x = rep(0:1, each = 3), 
                 y = c(0, 2, 2.1), 
                 z = paste("Example", 1:3))

p <- ggplot(df, aes(x, y, label = z, group = z)) + ylim(c(0, 2.5))

p <- p + geom_labelline(
  size = 8, boxcolour = NA,
  fill = theme_get()$panel.background$fill,
  label.padding = unit(0, "pt")
) 
p
```

![](https://i.imgur.com/LV5mKXF.png)

<sup>Created on 2022-01-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

> such as collision detection etc

Collision detection would be nice, but I indeed think it would be overkill. We could use `polyclip::pointinpolygon()` in combination with our curved textboxes to check if they overlap, but the problem here is that you have to cross-check every textbox with every other textbox, which can be quite expensive to do every time the window is resized. All in all I think collision detection could go in the low importance low urgency part of the [Eisenhower matrix](https://en.wikipedia.org/wiki/Time_management#The_Eisenhower_Method).

> I have added a scales.R file that allows a full range of hjust and vjust scale functions.

I think the scales are a good idea but there are a two things I'm concerned about.

1. We're inadvertently changing the behaviour of vanilla ggplot2. In the example below, once we load {geomtextpath} the output of the plot is changed. Notice how in the first bit the ABC and GHI labels do not touch the x = 1 and x = 3 points. Whereas after we load our package, the `hjust` is rescaled to the [0,1] interval and the labels do touch those points.

``` r
library(ggplot2)

df <- data.frame(
  x = 1:3,
  xend = 1:3 + 0.5,
  y = 0,
  yend = 0,
  label = c("ABC", "DEF", "GHI")
)

p <- ggplot(df, aes(x, y, label = label)) +
  geom_text(aes(hjust = c(-1, 0.5, 2)))
p
```

![](https://i.imgur.com/ccW6aqa.png)

``` r
library(geomtextpath)
p
```

![](https://i.imgur.com/WAsWCe8.png)

<sup>Created on 2022-01-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2. I think the default guide for these scales should be the `"none"` guide. You can see in the example above that the guide adds absolutely nothing to the understanding of the plot.

**Comment by AllanCameron** [comment]
Thanks Teun

I completely agree with your sentiments here. I don't think we can or should work too hard on the problem of overplotting, other than providing some options to allow users the ability to easily shift the labels around. The example that you give of using labels for masking works quite well, but would apply equally well to plain old `geom_text`, and the ggplot authors haven't bothered to implement any automation of this, so I don't think we need to either.

> I think the easiest solution to this problem, is to simply delete the scale_{h/v}just_continuous() variant

I hadn't noticed this effect on vanilla ggplot, and I think you're right - I will delete the continuous variants.

> I think the default guide for these scales should be the "none" guide.

I thought the guides were already defaulted to "none", but clearly they aren't. I will make the necessary changes.

**Comment by AllanCameron** [comment]
I have made the changes discussed above.

In addition, I have added the ability to remove text from paths that are not long enough to support them. Unfortunately this means another parameter and has to be done inside `makeContent`. However, the calculation isn't expensive, and only occurs when the new parameter, `remove_long` is set set to `TRUE`. 

The main reason for doing this was horrendous overplotting in `geom_textsf`. Without this technique, the plot looked like this:
``` r
df <- data.frame(x = c(-4.2518, -3.1883), 
                 y = c(55.8642, 55.9533),
                 label = c("Glasgow", "Edinburgh"))

ggplot(data = df) +
  geom_textsf(data = waterways,
              aes(label = name), text_smoothing = 99.5, linecolour = "#8888B3", 
              color = "gray30", hjust = 0.25, vjust = -0.5, fill = "#E6F0B3", 
              alpha = 0.8, fontface = 3, size = 3) + 
  geom_point(aes(x, y), data = df, color = "gray50", size = 3) + 
  geom_textpath(aes(x, y, label = label), color = "gray50",
                hjust = c(-0.2, 1.2)) +
  theme(panel.grid = element_line()) + 
  lims(x = c(-4.7, -3), y = c(55.62, 56.25))
```

![image](https://user-images.githubusercontent.com/33987720/147928849-11b622ef-acde-48e5-847d-4a6e30dde414.png)

But with the new technique the same plot looks like this:

![image](https://user-images.githubusercontent.com/33987720/147929076-ebf1509b-bc98-4750-8bb4-7352a9501518.png)
