### ISSUE TITLE
geom_hline and geom_vline

### ISSUE THREAD

**Issue by akarlinsky** [AllanCameron/geomtextpath#51]
First - this is FANTASTIC and absolutely BEAUTIFUL. 
I was wondering if there's an geomtextpath equivariant for geom_hline() and geom_vline which I frequently use to denote some descriptive stat such as mean, max, minimum, median etc in a density, scatter or bar plot.

**Comment by akarlinsky** [comment]
For now I've "hacked" it geom_textsegment.
Would you like a contribution of geom_texthline and geom_textvline based on geom_textsegment? I can give it a go :)

**Comment by teunbrand** [comment]
Just making a small note here: if we do this, we might as well do `geom_abline()`.

**Comment by AllanCameron** [comment]
Hi @akarlinsky and thanks for your kind words. We weren't too fussed about creating hline and vline variants because these never need to be curved. However, the direct labelling and broken line aspects might make these useful additions.

You are correct that the approach to this is via geom_textsegment. I have just written the implementation and documentation for geom_texthline and will do the same for geom_textvline.

The current behaviour is:
``` r
library(geomtextpath)
#> Loading required package: ggplot2

ggplot(mtcars, aes(mpg, disp)) + 
  geom_point() + 
  geom_texthline(yintercept = 200, label = "Threshold", hjust = 0.8)
```

![](https://i.imgur.com/KVZGBpt.png)

<sup>Created on 2022-01-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


@teunbrand it is straightforward to implement these, so for completeness I agree that geom_textabline and geom_labelabline should be added too.

**Comment by akarlinsky** [comment]
Amazing! so is this (geom_texthline) already on the current git version?

**Comment by AllanCameron** [comment]
Yes, @akarlinsky - just reinstall and it's good to go.

**Comment by AllanCameron** [comment]
@akarlinsky ghe latest commit includes `geom_textvline` and `geom_labelvline`.

So now you can do:
``` r
library(geomtextpath)
#> Loading required package: ggplot2

ggplot(mtcars, aes(mpg, disp)) + 
  geom_point() + 
  geom_texthline(yintercept = 200, label = "displacement threshold", 
                 hjust = 0.8, color = "red4") +
  geom_textvline(xintercept = 20, label = "consumption threshold", hjust = 0.8,
                 linetype = 2, vjust = 1.2, color = "blue4")
```

![](https://i.imgur.com/SRrR6gv.png)

<sup>Created on 2022-01-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by akarlinsky** [comment]
FANTASTIC. You have no idea how useful this is. 
It used to be a pain to h/vline and then annotating it accordingly. 
From my end I think the issue is closed, I think the new functions should be added to the main README.

Thanks again!

**Comment by AllanCameron** [comment]
Thanks for the suggestion @akarlinsky. I have added these geoms to the table in the readme and included the above example too. @teunbrand I'll add the `geom_textabline` and `geom_labelabline` over the next couple of days plus some unit tests.

**Comment by teunbrand** [comment]
Nice work Allan, very quick too! I'm not in a hurry with `geom_textabline()`, take all the time you need :)
