### ISSUE TITLE
`label` aesthetic in `geom_textdensity2d`

### ISSUE THREAD

**Issue by dhicks** [AllanCameron/geomtextpath#90]
I'm trying to use `geom_textdensity2d()` as a hack to direct label selected groups of points in a scatterplot with lots of distant outliers and several other groups.  But the geom doesn't accept the `label` aesthetic / doesn't appear to have a way to display labels as anything other than the contour values.  I did peek at `geom_textcontour()`, but it also doesn't appear to accept a `label` aesthetic. 

MWE:
```
library(tidyverse)
library(geomtextpath)

library(palmerpenguins)

data('penguins')

ggplot(penguins, aes(bill_length_mm, 
                     flipper_length_mm, 
                     color = species)) +
    geom_point(alpha = 0.5) +
    ## Generates a single contour line around most of the points in the groups of interest, 
    ## without trying to include outliers
    # geom_density_2d(data = ~ filter(.x, 
    #                                 species %in% c('Adelie', 'Gentoo')),
    #                 breaks = .001) +
    ## This doesn't work because the geom doesn't recognize the label aesthetic
    geom_textdensity2d(aes(label = species),
                       breaks = .001,
                       data = ~ filter(.x,
                                       species %in% c('Adelie', 'Gentoo')))
```

**Comment by AllanCameron** [comment]
Thanks for getting in touch. You are right about `geom_textdensity2d` - the labels are hard-coded in the `setup_data` function to take the value of the level represented by the contour. It's quite difficult to avoid this, because typically there are several contours per group of points, and it is not clear how labels in the data could be mapped to these. It makes sense with a single contour such as in your example, but this is a bit niche.

`geom_textcontour` _does_ accept labels, but only one per group. If you wanted to use density, then you could do it manually as follows:
```r
library(tidyverse)
library(geomtextpath)
library(palmerpenguins)

data('penguins')

dens <- with(penguins[complete.cases(penguins) & penguins$species == "Adelie",],
             MASS::kde2d(bill_length_mm, flipper_length_mm, n = 50)
)

adel <- data.frame(flipper_length_mm = rep(dens$y, 50),
                   bill_length_mm = rep(dens$x, each = 50),
                   z = c(t(dens$z)), species = "Adelie")

dens <- with(penguins[complete.cases(penguins) & penguins$species == "Gentoo",],
             MASS::kde2d(bill_length_mm, flipper_length_mm, n = 50)
)

gent <- data.frame(flipper_length_mm = rep(dens$y, 50),
                   bill_length_mm = rep(dens$x, each = 50),
                   z = c(t(dens$z)), species = "Gentoo")

ggplot(penguins, aes(bill_length_mm, 
                     flipper_length_mm, 
                     color = species)) +
  geom_point(alpha = 0.5) +
  geom_textcontour(aes(label = species, z = z), breaks = .001, data = adel,
                   hjust = 0.4) +
  geom_textcontour(aes(label = species, z = z), breaks = .002, data = gent)
```
![image](https://user-images.githubusercontent.com/33987720/227738559-011a9876-3665-40ee-b716-1007616112e3.png)

I accept that this is a bit convoluted, but it seems to me to be an acceptable work-around for a relatively unusual use-case.

**Comment by dhicks** [comment]
Yeah, that approach makes a lot of sense.  Now I just need to figure out the best way to wrap everything in functions for my use-case.  Thanks! Feel free to close.
